import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteNavbar from "@/components/ui/site-navbar";
import BackgroundShapes from "@/components/ui/background-shapes";
import BackButton from "@/components/ui/back-button";
import PagePaddingWrapper from "@/components/ui/page-padding-wrapper";
import FloatingCreateButton from "@/components/ui/floating-create-button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BackgroundShapes />
        <BackButton />
        <FloatingCreateButton />
        <PagePaddingWrapper>{children}</PagePaddingWrapper>
        <SiteNavbar />
      </body>
    </html>
  );
}
